# Generated by Django 3.1.4 on 2021-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'staff'), ('3', 'customer')], default='3', max_length=20),
        ),
    ]
