# Generated by Django 3.1.4 on 2021-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210608_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
