# Generated by Django 3.1.4 on 2021-08-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210811_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='on_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='successful_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'created'), ('2', 'on_delivery'), ('3', 'successful'), ('4', 'unsuccessful')], default='1', max_length=20),
        ),
    ]
