# Generated by Django 3.1.4 on 2021-08-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210811_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('1', 'is_ordered'), ('2', 'is_payed'), ('3', 'on_delivery'), ('4', 'successful'), ('5', 'unsuccessful')], default='1', max_length=20),
        ),
    ]
