# Generated by Django 3.1.4 on 2021-08-11 06:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210811_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default=users.models.create_new_ref_number, max_length=10, unique=True),
        ),
    ]
