# Generated by Django 3.1.4 on 2021-08-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210817_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aaddress',
            new_name='address',
        ),
    ]
