# Generated by Django 3.1.4 on 2021-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210817_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
