# Generated by Django 3.1.4 on 2021-09-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.company_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.shop_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', djrichtextfield.models.RichTextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d')),
                ('video', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, db_column='description_en', null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('ingredients_en', models.TextField(blank=True, db_column='ingredients_en', null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('usage_en', models.TextField(blank=True, db_column='usage_en', null=True)),
                ('caution', models.TextField(blank=True, null=True)),
                ('caution_en', models.TextField(blank=True, db_column='caution_en', null=True)),
                ('storage', models.TextField(blank=True, null=True)),
                ('storage_en', models.TextField(blank=True, db_column='storage_en', null=True)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=items.models.poster_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='items.Category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_created_by', to=settings.AUTH_USER_MODEL)),
                ('shops', models.ManyToManyField(blank=True, null=True, to='items.Shop')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='items.Tag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
