# Generated by Django 3.1.4 on 2021-09-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210917_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.type')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='items.Type'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='items.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='items.SubCategory'),
        ),
    ]
