# Generated by Django 3.1.4 on 2021-09-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210917_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='type',
            new_name='category',
        ),
    ]
