# Generated by Django 3.1.4 on 2021-08-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_item_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
