# Generated by Django 3.1.4 on 2021-08-09 02:06

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.poster_directory_path),
        ),
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
