# Generated by Django 3.1.4 on 2021-08-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20210810_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
