# Generated by Django 3.1.4 on 2021-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20210813_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
