# Generated by Django 3.1.4 on 2021-08-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20210818_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_brand',
            new_name='is_featured',
        ),
    ]
